name: CI-PR

on:
  push:
    branches:
      - "main"

jobs:
  build-docker:
    name: Build docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Hadolint
        uses: hadolint/hadolint-action@v1.6.0
        with:
          dockerfile: Dockerfile

      - name: Build an image from Dockerfile
        run: |
          docker build -t lansweeperdev/namechecker:${{ github.sha }} .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "lansweeperdev/namechecker:${{ github.sha }}"
          format: "table"
          exit-code: "1"
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "CRITICAL,HIGH"

  build-tests:
    name: Build and tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "14.17"

      - name: Install dependencies
        run: yarn

      - name: Lint
        run: yarn lint

      - name: Build
        run: yarn build

      - name: Tests
        run: yarn test:ci

      - name: E2E install cypress
        run: yarn cypress:install

      - name: E2E Start server in background
        run: |
          yarn run start &
          sleep 5 && curl http://localhost:3000 -I
        env:
          DISABLE_REDIS: true
          SESSION_SECRET: ${{ secrets.E2E_SESSION_SECRET }}
          LS_APP_NAME: NameChecker
          LS_APP_CLIENT_ID: ${{ secrets.E2E_LS_APP_CLIENT_ID }}
          LS_APP_CLIENT_SECRET: ${{ secrets.E2E_LS_APP_CLIENT_SECRET }}
          LS_APP_CALLBACK_URI: http://localhost:3000/api/callback
          LS_APP_AUTHORIZE_URI: https://appstag.lansweeper.com/authorize-app/${{ secrets.E2E_LS_APP_CLIENT_ID }}?forceAuthorize=true
          INTEGRATIONS_GATEWAY_HOST: https://apistag.lansweeperdev.com/api/integrations

      - name: Execute E2E tests
        run: |
          yarn cypress:run
        env:
          CYPRESS_USER: ${{ secrets.E2E_USER }}
          CYPRESS_PASSWORD: ${{ secrets.E2E_USER_PASSWORD }}
          CYPRESS_SITE_ONE: ${{ secrets.E2E_SITE_ONE }}
          CYPRESS_SITE_TWO: ${{ secrets.E2E_SITE_TWO }}

  release:
    name: Release and push docker image
    runs-on: ubuntu-latest
    needs: [build-tests, build-docker]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "14.17"

      - name: Install dependencies
        run: yarn

      - name: Release
        run: yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.ADMIN_GITHUB_PERSONAL_TOKEN }}

      - name: Extract version from package.json
        uses: sergeysova/jq-action@v2
        id: version
        with:
          cmd: "jq .version package.json -r"

      - name: docker login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: lansweeperdev/namechecker:latest,lansweeperdev/namechecker:${{ steps.version.outputs.value }}
