name: CI-PR

on:
  push:
    branches:
      - "main"

jobs:
  build-docker:
    name: Build docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Hadolint
        uses: hadolint/hadolint-action@v1.6.0
        with:
          dockerfile: Dockerfile

      - name: Build an image from Dockerfile
        run: |
          docker build -t lansweeper-public/namechecker:${{ github.sha }} .

      - name: Install trivy
        run: |
          if [[ $EUID == 0 ]]; then export SUDO=""; else export SUDO="sudo"; fi
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | $SUDO sh -s -- -b /usr/local/bin

      - name: Run Trivy vulnerability scanner
        run: |
          trivy image --no-progress --exit-code 1 \
            --severity HIGH,CRITICAL \
            --vuln-type os,library \
            --ignore-unfixed true \
            --ignorefile .trivyignore \
            lansweeper-public/namechecker:${{ github.sha }}

  build-tests:
    name: Build and tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "14.17"

      - name: Install dependencies
        run: yarn

      - name: Lint
        run: yarn lint

      - name: Build
        run: yarn build

      - name: Tests
        run: yarn test

      - name: E2E tests install cypress and start server
        run: yarn cypress:install && yarn run start &

      - name: Run E2E tests
        run: yarn run start &

  release:
    name: Release and push docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "14.17"

      - name: docker login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_HUB_TOKEN}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      - name: Install dependencies
        run: yarn

      - name: Release
        run: yarn release

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag lansweeper-public/namechecker:${{ github.sha }}

      - name: Docker Push
        run: docker push lansweeper-public/namechecker
