name: CI-PR

on: [pull_request]

jobs:
  build-docker:
    name: Build docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Hadolint
        uses: hadolint/hadolint-action@v1.6.0
        with:
          dockerfile: Dockerfile

      - name: Build an image from Dockerfile
        run: |
          docker build -t lansweeperdev/namechecker:${{ github.sha }} .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "lansweeperdev/namechecker:${{ github.sha }}"
          format: "table"
          exit-code: "1"
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "CRITICAL,HIGH"

  build-tests:
    name: Build and tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "14.17"

      - name: Install dependencies
        run: yarn

      - name: Lint
        run: yarn lint

      - name: Build
        run: yarn build

      - name: Tests
        run: yarn test:ci

      - name: E2E tests install cypress and start server
        run: yarn cypress:install && yarn run start &

      - name: Run E2E tests
        run: yarn cypress:run
        env:
          CYPRESS_USER: ${{ secrets.E2E_USER }}
          CYPRESS_PASSWORD: ${{ secrets.E2E_USER_PASSWORD }}
          CYPRESS_SITE_ONE: ${{ secrets.E2E_SITE_ONE }}
          CYPRESS_SITE_TWO: ${{ secrets.E2E_SITE_TWO }}
          DISABLE_REDIS: true
          LS_APP_NAME: NameChecker
          LS_APP_CLIENT_ID: ${{ secrets.E2E_LS_APP_CLIENT_ID }}
          LS_APP_CLIENT_SECRET: ${{ secrets.E2E_LS_APP_CLIENT_SECRET }}
          LS_APP_CALLBACK_URI: http://localhost:3000/api/callback
          LS_APP_AUTHORIZE_URI: https://appstag.lansweeper.com/authorize-app/${{ secrets.E2E_LS_APP_CLIENT_ID }}?forceAuthorize=true
          INTEGRATIONS_GATEWAY_HOST: https://apistag.lansweeperdev.com/api/integrations
